"""Typer CLI for ``codegraph harness`` commands."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer

from codegraph.harness.artifacts import ArtifactManager
from codegraph.harness.manifest import list_builtin_manifests, manifest_for
from codegraph.harness.runner import HarnessRunner
from codegraph.harness.store import RunStore

harness_app = typer.Typer(
    help="Run and inspect Harness modules.",
    no_args_is_help=True,
)

_CLI_MODULE_ORDER: tuple[str, ...] = (
    "workflow.impact",
    "workflow.test_audit",
    "workflow.explain",
    "workflow.find",
    "enrich.prepare",
    "benchmark.gate",
    "doctor.run",
)

_CLI_MODULE_SUMMARY: dict[str, str] = {
    "workflow.impact": "Run impact workflow",
    "workflow.test_audit": "Run test audit workflow",
    "workflow.explain": "Explain symbol/file",
    "workflow.find": "Find symbol",
    "enrich.prepare": "Prepare enrichment input",
    "benchmark.gate": "Run/read benchmark gate",
    "doctor.run": "Run doctor through harness",
}


def _status_label(module_id: str) -> str:
    manifest = manifest_for(module_id)
    return "stable" if manifest.is_stable else "reserved"


def _resolve_project_root(root: str | None) -> Path:
    if root:
        return Path(root).resolve()

    start = Path.cwd().resolve()
    for parent in [start] + list(start.parents):
        cg_dir = parent / ".codegraph"
        if (
            (cg_dir / "index.sqlite").exists()
            or (cg_dir / "graph.json").exists()
            or (cg_dir / "runs").exists()
        ):
            return parent
    return start


def _resolve_store_for_run(run_id: str, root: str | None) -> RunStore:
    if root is not None:
        return RunStore(project_root=_resolve_project_root(root))

    start = Path.cwd().resolve()
    for parent in [start] + list(start.parents):
        run_state = parent / ".codegraph" / "runs" / run_id / "state.json"
        if run_state.exists():
            return RunStore(project_root=parent)
    return RunStore(project_root=_resolve_project_root(root))


def _summary_for(module_id: str, description: str) -> str:
    return _CLI_MODULE_SUMMARY.get(module_id, description)


def _ordered_doc_manifests() -> list[Any]:
    manifest_map = {manifest.id: manifest for manifest in list_builtin_manifests()}
    ordered_ids = list(_CLI_MODULE_ORDER)
    ordered_ids.extend(
        manifest_id
        for manifest_id in sorted(manifest_map)
        if manifest_id not in _CLI_MODULE_ORDER
    )
    return [manifest_map[manifest_id] for manifest_id in ordered_ids]


def _exit_cli_error(message: str) -> None:
    typer.echo(f"Error: {message}", err=True)
    raise typer.Exit(1)


def _load_json_input(input_path: Path) -> dict[str, Any]:
    if not input_path.exists():
        raise typer.BadParameter(f"Input file not found: {input_path}")
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise typer.BadParameter(f"Invalid JSON in {input_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise typer.BadParameter(
            f"Input file must contain a JSON object: {input_path}"
        )
    return payload


def _merge_run_input(
    *,
    base: dict[str, Any],
    files: str | None,
    symbols: str | None,
    change_type: str | None,
    description: str | None,
    include_tests: bool | None,
    limit: int | None,
    repair: bool | None,
) -> dict[str, Any]:
    payload = dict(base)
    if files is not None:
        payload["files"] = files
    if symbols is not None:
        payload["symbols"] = symbols
    if change_type is not None:
        payload["change_type"] = change_type
    if description is not None:
        payload["description"] = description
    if include_tests is not None:
        payload["include_tests"] = include_tests
    if limit is not None:
        payload["limit"] = limit
    if repair is not None:
        payload["repair"] = repair
    return payload


def _render_module_docs() -> str:
    lines = [
        "# Harness Modules",
        "",
        "Generated by `codegraph harness docs`.",
        "",
        "## Command Surface",
        "",
        "```text",
        "codegraph harness list",
        "codegraph harness run <module> --input input.json",
        "codegraph harness status <run-id>",
        "codegraph harness artifacts <run-id>",
        "```",
        "",
        "## Modules",
        "",
    ]
    for manifest in _ordered_doc_manifests():
        module_id = manifest.id
        lines.extend(
            [
                f"### `{module_id}`",
                "",
                f"- Status: `{_status_label(module_id)}`",
                f"- Category: `{manifest.category}`",
                f"- Summary: {_summary_for(module_id, manifest.description)}",
                f"- Description: {manifest.description}",
                f"- Version: `{manifest.version}`",
                f"- Default artifacts: `{', '.join(manifest.default_artifacts)}`",
                f"- Persist by default: `{manifest.persist_by_default}`",
                f"- Supports checkpoints: `{manifest.supports_checkpoints}`",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


@harness_app.command("list")
def harness_list() -> None:
    """List the Harness modules exposed through the CLI."""
    for module_id in _CLI_MODULE_ORDER:
        status = _status_label(module_id)
        typer.echo(
            f"{module_id:<22} {status:<10} {_CLI_MODULE_SUMMARY[module_id]}"
        )


@harness_app.command("run")
def harness_run(
    module_id: str = typer.Argument(..., help="Harness module id, e.g. workflow.impact"),
    input_path: str | None = typer.Option(
        None,
        "--input",
        help="Path to a JSON object used as run input.",
    ),
    files: str | None = typer.Option(
        None,
        "--files",
        help="Comma-separated file paths for workflow modules.",
    ),
    symbols: str | None = typer.Option(
        None,
        "--symbols",
        help="Comma-separated symbols for workflow modules.",
    ),
    change_type: str | None = typer.Option(
        None,
        "--change-type",
        help="Change type for workflow.impact.",
    ),
    description: str | None = typer.Option(
        None,
        "--description",
        help="Optional free-form change description.",
    ),
    include_tests: bool | None = typer.Option(
        None,
        "--include-tests/--no-include-tests",
        help="Include or exclude test recommendations where supported.",
    ),
    limit: int | None = typer.Option(
        None,
        "--limit",
        min=1,
        help="Limit workflow result counts where supported.",
    ),
    repair: bool | None = typer.Option(
        None,
        "--repair/--no-repair",
        help="Pass repair=true to doctor.run.",
    ),
    root: str | None = typer.Option(
        None,
        "--root",
        help="Project root containing .codegraph.",
    ),
) -> None:
    """Run a Harness module and persist the run."""
    payload: dict[str, Any] = {}
    try:
        if input_path is not None:
            payload = _load_json_input(Path(input_path).resolve())
    except typer.BadParameter as exc:
        _exit_cli_error(str(exc))
    payload = _merge_run_input(
        base=payload,
        files=files,
        symbols=symbols,
        change_type=change_type,
        description=description,
        include_tests=include_tests,
        limit=limit,
        repair=repair,
    )
    try:
        result = HarnessRunner().run(
            module_id,
            payload,
            project_root=_resolve_project_root(root),
        )
    except ValueError as exc:
        _exit_cli_error(str(exc))

    typer.echo(f"run_id: {result.run_id}")
    typer.echo(f"module: {result.module_id}")
    typer.echo(f"status: {result.status.value}")
    if result.artifacts:
        typer.echo(f"artifacts: {', '.join(result.artifacts)}")
    if result.error:
        typer.echo(f"error: {result.error}", err=True)
        raise typer.Exit(1)


@harness_app.command("status")
def harness_status(
    run_id: str = typer.Argument(..., help="Run id under .codegraph/runs/."),
    root: str | None = typer.Option(
        None,
        "--root",
        help="Project root containing .codegraph.",
    ),
) -> None:
    """Read and print a persisted run state."""
    try:
        store = _resolve_store_for_run(run_id, root)
        state = store.load_run(run_id)
    except ValueError as exc:
        _exit_cli_error(str(exc))
    if state is None:
        _exit_cli_error(f"Run not found: {run_id}")

    typer.echo(f"run_id: {state.run_id}")
    typer.echo(f"module: {state.module_id}")
    typer.echo(f"status: {state.status.value}")
    typer.echo(f"project_root: {state.project_root}")
    if state.started_at:
        typer.echo(f"started_at: {state.started_at}")
    if state.finished_at:
        typer.echo(f"finished_at: {state.finished_at}")
    if state.output_path:
        typer.echo(f"output_path: {state.output_path}")
    if state.error:
        typer.echo(f"error: {state.error}")


@harness_app.command("artifacts")
def harness_artifacts(
    run_id: str = typer.Argument(..., help="Run id under .codegraph/runs/."),
    root: str | None = typer.Option(
        None,
        "--root",
        help="Project root containing .codegraph.",
    ),
) -> None:
    """List artifact files for a run."""
    try:
        store = _resolve_store_for_run(run_id, root)
        run_dir = store.run_dir(run_id)
    except ValueError as exc:
        _exit_cli_error(str(exc))
    if not run_dir.exists():
        _exit_cli_error(f"Run not found: {run_id}")

    artifacts = ArtifactManager(store.artifacts_dir(run_id)).list_artifacts()
    if not artifacts:
        typer.echo("No artifacts.")
        return

    for artifact in artifacts:
        typer.echo(f"{artifact.name}\t{artifact.media_type}\t{artifact.size_bytes}B")


@harness_app.command("docs")
def harness_docs(
    root: str | None = typer.Option(
        None,
        "--root",
        help="Project root where docs/harness-modules.md will be generated.",
    ),
) -> None:
    """Generate harness module documentation."""
    project_root = _resolve_project_root(root)
    docs_path = project_root / "docs" / "harness-modules.md"
    docs_path.parent.mkdir(parents=True, exist_ok=True)
    docs_path.write_text(_render_module_docs(), encoding="utf-8")
    typer.echo(f"Generated: {docs_path}")
